#ifndef XPADUSBLIBRARY_GLOBAL_H
#define XPADUSBLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XPADUSBLIBRARY_LIBRARY)
#  define XPADUSBLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XPADUSBLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XPADUSBLIBRARY_GLOBAL_H
